// SutraKriti product catalogue (MVP).
// Each product supports either a single `image` OR an `images: [...]` array.
// The frontend automatically shows a swipeable gallery when more than one image is present.
export const PRODUCTS = [
  {
    id: 'p-tote-terracotta',
    name: 'Terracotta Tote Bag',
    category: 'Handbags',
    price: 2499,
    images: [
      'https://images.pexels.com/photos/10820406/pexels-photo-10820406.jpeg',
      'https://images.pexels.com/photos/30224898/pexels-photo-30224898.jpeg',
      'https://images.unsplash.com/photo-1560347964-838d2f63cdc0',
    ],
    colors: ['Terracotta', 'Cream'],
    description: 'A generous everyday tote hand-crocheted from soft cotton yarn in warm terracotta tones. Reinforced base, roomy interior and heirloom stitching.',
    material: '100% Cotton Yarn',
    dimensions: '34 × 32 × 12 cm',
    care: 'Hand wash cold, reshape while damp, dry flat.',
    delivery: '7–10 days',
    new: true,
  },
  {
    id: 'p-tote-cream',
    name: 'Ivory Market Tote',
    category: 'Handbags',
    price: 2299,
    images: [
      'https://images.pexels.com/photos/30224898/pexels-photo-30224898.jpeg',
      'https://images.pexels.com/photos/10820406/pexels-photo-10820406.jpeg',
    ],
    colors: ['Ivory', 'Beige'],
    description: 'A soft ivory market tote with an artisanal open weave — light, breathable and effortlessly elegant.',
    material: 'Cotton & Linen blend',
    dimensions: '32 × 30 × 10 cm',
    care: 'Hand wash, dry flat.',
    delivery: '7–10 days',
  },
  {
    id: 'p-potli-gold',
    name: 'Golden Wedding Potli',
    category: 'Potli Bags',
    price: 1899,
    images: [
      'https://images.pexels.com/photos/32452334/pexels-photo-32452334.jpeg',
      'https://images.unsplash.com/photo-1510284876186-b1a84b94418f',
    ],
    colors: ['Gold', 'Ivory'],
    description: 'A ceremonial potli with delicate crochet lace and a golden drawstring — perfect for weddings and festive gifting.',
    material: 'Cotton with gold thread',
    dimensions: '18 × 22 cm',
    care: 'Spot clean only.',
    delivery: '10–14 days',
    bestseller: true,
  },
  {
    id: 'p-flowers-bouquet',
    name: 'Everlasting White Blossom Bouquet',
    category: 'Flowers',
    price: 3499,
    images: [
      'https://images.unsplash.com/photo-1645516956968-dee62f4a9090',
      'https://images.pexels.com/photos/20269075/pexels-photo-20269075.jpeg',
    ],
    colors: ['Ivory', 'Sage'],
    description: 'A delicate bouquet of hand-crocheted white blossoms — anemones and jasmine-inspired blooms nestled in a soft glass vessel. A quiet, timeless keepsake that will never wilt.',
    material: 'Soft cotton & acrylic yarn',
    dimensions: '12 blooms, ~30 cm',
    care: 'Dust gently.',
    delivery: '10–14 days',
    bestseller: true,
  },
  {
    id: 'p-flowers-single',
    name: 'Wildflower Posy',
    category: 'Flowers',
    price: 799,
    images: [
      'https://images.pexels.com/photos/20269075/pexels-photo-20269075.jpeg',
      'https://images.unsplash.com/photo-1645516956968-dee62f4a9090',
    ],
    colors: ['Mustard', 'Blush', 'Sage'],
    description: 'A charming hand-crocheted posy of mixed wildflowers — cheerful blooms in warm, sunlit hues, tied together like a memory of summer. A tiny bouquet you can keep forever.',
    material: 'Cotton yarn',
    dimensions: '~25 cm bunch',
    care: 'Dust gently.',
    delivery: '5–7 days',
    new: true,
  },
  {
    id: 'p-blanket-bouquet',
    name: 'Bouquet Blanket',
    category: 'Home Decor',
    price: 5999,
    images: [
      'https://images.unsplash.com/photo-1571434976902-a6e3e1eb0d51',
      'https://images.pexels.com/photos/5806996/pexels-photo-5806996.jpeg',
      'https://images.pexels.com/photos/18971489/pexels-photo-18971489.jpeg',
    ],
    colors: ['Ivory', 'Terracotta'],
    description: 'Our signature bouquet blanket — a soft, sculptural throw crocheted flower-by-flower with love.',
    material: 'Merino wool blend',
    dimensions: '120 × 150 cm',
    care: 'Dry clean recommended.',
    delivery: '3–4 weeks',
    bestseller: true,
  },
  {
    id: 'p-blanket-sage',
    name: 'Sage Throw Blanket',
    category: 'Home Decor',
    price: 4499,
    images: [
      'https://images.pexels.com/photos/5806996/pexels-photo-5806996.jpeg',
      'https://images.unsplash.com/photo-1571434976902-a6e3e1eb0d51',
    ],
    colors: ['Sage', 'Cream'],
    description: 'A calming sage throw with a modern granny stitch — cozy for the couch, elegant for the bed.',
    material: 'Wool & Cotton',
    dimensions: '130 × 160 cm',
    care: 'Hand wash cold.',
    delivery: '3–4 weeks',
  },
  {
    id: 'p-decor-hoop',
    name: 'Woven Wall Hoop',
    category: 'Home Decor',
    price: 1599,
    images: [
      'https://images.pexels.com/photos/18971489/pexels-photo-18971489.jpeg',
      'https://images.pexels.com/photos/36238478/pexels-photo-36238478.jpeg',
    ],
    colors: ['Cream', 'Brown'],
    description: 'A textured wall hoop that adds a handcrafted warmth to any room.',
    material: 'Cotton & Bamboo',
    dimensions: '30 cm diameter',
    care: 'Dust gently.',
    delivery: '7–10 days',
  },
]

// Convenience: give every product a top-level `image` (first of gallery) so old
// consumers keep working without changes.
for (const p of PRODUCTS) {
  if (!p.image && p.images?.length) p.image = p.images[0]
}
